
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 20;
  public static final int ELSE = 3;
  public static final int CONSTSTRING = 23;
  public static final int OR = 21;
  public static final int INT = 12;
  public static final int CHAR = 13;
  public static final int WHILE = 4;
  public static final int SCANF = 11;
  public static final int RETURN = 8;
  public static final int DOBLEPUNTOS = 33;
  public static final int IF = 2;
  public static final int PRINTF = 10;
  public static final int ID = 25;
  public static final int APUNTADOR = 14;
  public static final int OPMULT = 16;
  public static final int COMMA = 27;
  public static final int ASIGNACION = 18;
  public static final int EOF = 0;
  public static final int APUNTADORVAR = 26;
  public static final int AUTOINCREMENTOS = 17;
  public static final int MAIN = 6;
  public static final int BREAK = 7;
  public static final int CONSTCHAR = 24;
  public static final int error = 1;
  public static final int SINTERROGACION = 34;
  public static final int PUNTOCOMA = 28;
  public static final int INTEGER = 22;
  public static final int RPAR = 30;
  public static final int OPSUM = 15;
  public static final int FOR = 5;
  public static final int OPREL = 19;
  public static final int VOID = 9;
  public static final int DERLLAVE = 32;
  public static final int IZQLLAVE = 31;
  public static final int LPAR = 29;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "ELSE",
  "WHILE",
  "FOR",
  "MAIN",
  "BREAK",
  "RETURN",
  "VOID",
  "PRINTF",
  "SCANF",
  "INT",
  "CHAR",
  "APUNTADOR",
  "OPSUM",
  "OPMULT",
  "AUTOINCREMENTOS",
  "ASIGNACION",
  "OPREL",
  "AND",
  "OR",
  "INTEGER",
  "CONSTSTRING",
  "CONSTCHAR",
  "ID",
  "APUNTADORVAR",
  "COMMA",
  "PUNTOCOMA",
  "LPAR",
  "RPAR",
  "IZQLLAVE",
  "DERLLAVE",
  "DOBLEPUNTOS",
  "SINTERROGACION"
  };
}

